### ISSUE TITLE
PTC Login 

### ISSUE THREAD

**Issue by jsavoy3** [BoBeR182/PoGoBoWo#23]
When trying to login using a PTC account I'm receiving a json error at startup "no .json file to decode".  This started occurring after updating to this commit https://github.com/BoBeR182/PoGoBoWo/commit/0ca0ea9d7c82c8e8512bb2fcafb1e3cb6b688fbd

**Comment by BoBeR182** [comment]
https://go.jooas.com/ Servers where down recently.
