### ISSUE TITLE
No fort to walk to!

### ISSUE THREAD

**Issue by fvbrandt** [BoBeR182/PoGoBoWo#26]
Anyone know what causes this? Right after starting the script I get these errors, no matter what location I use. The bot never starts moving. I have found numerous people reporting this bug in the old TomTheBotter repo and on reddit but nobody had a solution.

It happens in all the newer versions that are around, but I still have an old branch that reliably works. I.e. I can use the same config on the old branch and it works, but all newer versions have this problem.

In the versions that show the location via web gui I can also see that it doesn't detect any Pokestops in places where there should be many. I have debugged a bit and saw that here:

```
def spin_near_fort(self):
        map_cells = self.nearby_map_objects()['responses']['GET_MAP_OBJECTS']['map_cells']
        forts = PGoApi.flatmap(lambda c: c.get('forts', []), map_cells)
        destinations = filtered_forts(self._posf, forts)
```

the `forts` variable is already an empty list, even before filtering.

**Comment by BoBeR182** [comment]
My version does not have a GUI< can you confirm what commit you are using and please make sure you tried running the bot once with `--cache` at the end.

**Comment by fvbrandt** [comment]
When I run it with --cache I get:

[ERROR] Main loop has an ERROR, restarting 'map_cells'

which must be a KeyError. This is also something that I have seen other users report without a solution. It is probably the same underlying cause?

I know that your version does not have a GUI. It's just that this error appears in all the active forks that I have tried. I was introduced in one of the last commits of TomTheBotter that all the active forks still include.

For reference the issue exists in your commit 7325359. The working version I have is TomTheBotter's commit df993fd (2016-07-24).

**Comment by BoBeR182** [comment]
I'm having trouble replicating this, I left my bot on all night and it did it once on a PTC account, but the google account ran the same amount of time. Restarting my bot fixed it. Any one have locations that cause this to happen from the start and not randomly after 9h+ runtime.

**Comment by fvbrandt** [comment]
While trying to figure out which commit broke it I deleted my checkout completely before checking out the newest version and now I don't get the abovementioned errors anymore. I now get "The provided API key is invalid" from the Google API but at least it finds a fort to walk to now. It just doesn't find the route there. ;)
Might be there was some .gitignored file in auth/accounts that was incompatible between versions? No clue...
