### ISSUE TITLE
Authentication error OS X

### ISSUE THREAD

**Issue by NoteGo123** [BoBeR182/PoGoBoWo#27]
Hello.

I got an error when I run the script.
It seems like the script try to get information from the Json config, but it can't.

I got this:

Traceback (most recent call last):
  File "pokebot.py", line 105, in <module>
    main()
  File "pokebot.py", line 74, in main
    config = init_config()
  File "pokebot.py", line 49, in init_config
    required=required("auth_service"))
  File "pokebot.py", line 46, in required
    return x not in load['accounts'][0].keys()
KeyError: 'accounts'

**Comment by etrevis** [comment]
Have you renamed "config.json.example" to "config.json"? If yes check the config.json structure or modify again the example

**Comment by NoteGo123** [comment]
Yes.
Sorry, it worked if I go to the directory with the command cp before run the script. If I run the script with the directory address like: python /user/[user]/desktop/pokebot.py -i 0 doesn't work.

**Comment by BoBeR182** [comment]
cp is a copy command did you mean cd (change dirs)?

Please confirm this is error on the users environment and not the project code, or I will close this as invalid later.
