### ISSUE TITLE
Releasing pokemon at gym

### ISSUE THREAD

**Issue by etrevis** [BoBeR182/PoGoBoWo#28]
If all the conditions to release a pokemon are met, the bot try to release it also if currently in a gym.

**Comment by BoBeR182** [comment]
Can you post the error that you are getting, currently I have no gym support, and your pokemon that is in the gym is only getting released before the bot thinks its too weak.

**Comment by etrevis** [comment]
I don't get any error, simply the bot try to release it every cicle, but obviously Niantic doen't allow that. The Pokemon's calculated IV is 31.1, under the limit setted in config (MIN_IV 80, release_duplicate true, CP_forgivness .90 ) and also a duplicate of another pokemon with higher IV. These pokemon aren't trully weak (two golducks with 1392 and 1395 CP), but that's not the point. Bot shouldn't try to release pokemons at gyms ;)

**Comment by BoBeR182** [comment]
I see the issue now, I do not know how to check gym status of a pokemon, nor do I have any in a current gym. I will work on it once I get other features implemented

**Comment by etrevis** [comment]
If a pokemon is deployed at a gym its inventory states: `"deployed_fort_id": xxx` so adding a basic check before realesing it should be straightforward. I'll try now

**Comment by etrevis** [comment]
Done, upload in my develop branch
