### ISSUE TITLE
Scan Throattling

### ISSUE THREAD

**Issue by 750z** [BoBeR182/PoGoBoWo#42]
https://www.reddit.com/r/pokemongobotting/comments/4vftw9/if_your_bot_has_stopped_catching_pokemon_its/

Dont know if its been implemented, but I thought it would be a good idea to bring it up

**Comment by etrevis** [comment]
Oh thanks, i didn't know that, so this is why my map scan app doesn't work anymore.
Anyway in my [develop branch](https://github.com/etrevis/PoGo-Bot/tree/develop) i implemented the option "slow but stealth" that (indirectly) avoid the time limit.
