### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by cbogithub** [BoBeR182/PoGoBoWo#47]
raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by BoBeR182** [comment]
What operating system are you on?

**Comment by morefreeze** [comment]
I have met this problem yesterday. In a brute way, I solved it through installing `conda` and `conda create -n py27 python=2.7 anaconda` (This will cost almost 5GB space).
I guess your OS is CentOS, so your python version is 2.6.
I hope this can help you.

**Comment by cbogithub** [comment]
thanks for help but , i run it on window 10 ,

**Comment by BoBeR182** [comment]
Can you post the full error message? and steps I would need to do to replicate it?

**Comment by cbogithub** [comment]
i fixed it:

\lib\site-packages\gmaps\client.py


find line 74 :"\lib\site-packages\gmaps\client.py"

raw_response = requests.get(url, params=parameters)  ==> raw_response = requests.get(url, params=parameters,verify=False)

**Comment by BoBeR182** [comment]
Can you create a pull request I will be happy to merge your commit.
