### ISSUE TITLE
[ISSUE] Key error: Accounts

### ISSUE THREAD

**Issue by RovingSpirit** [BoBeR182/PoGoBoWo#63]
Traceback (most recent call last):
  File "pokebot.py", line 109, in <module>
    main()
  File "pokebot.py", line 76, in main
    config = init_config()
  File "pokebot.py", line 51, in init_config
    required=required("auth_service"))
  File "pokebot.py", line 48, in required
    return x not in load['accounts'][0].keys()
KeyError: 'accounts'

Running on Mac OSX, used a browser API key, was this correct? Thanks!

**Comment by BoBeR182** [comment]
Please post your config.json flie and what you did to start the bot. Seems like you made a error in your .json

**Comment by RovingSpirit** [comment]
{"accounts" :
    [{
        "auth_service": "google",
        "username": "xxx.xxx@gmail.com",
        "password": "xxxxx",
        "location": "Wynyard station, Sydney",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": ["AIzaSy------------------------------"],
        "MIN_KEEP_IV" : 80,
        "KEEP_CP_OVER": 600,
        "RELEASE_DUPLICATE": true,
        "DUPLICATE_CP_FORGIVENESS": 0.90,
        "STEP_SIZE": 100,
        "RETURN_START_INTERVAL": 20,
        "MAX_BALL_TYPE": 2,
        "SLOW_BUT_STEALTH": false,
        "AUTO_HATCHING": true,
        "WEB_PORT": 3001,
        "MIN_ITEM_COUNTS": {
            "ITEM_POKE_BALL": 15,
            "ITEM_GREAT_BALL": 25,
            "ITEM_ULTRA_BALL": 95,
            "ITEM_POTION": 0,
            "ITEM_SUPER_POTION": 5,
            "ITEM_HYPER_POTION": 30,
            "ITEM_MAX_POTION": 60,
            "ITEM_RAZZ_BERRY": 40,
            "ITEM_BLUK_BERRY": 0,
            "ITEM_NANAB_BERRY": 0,
            "ITEM_REVIVE": 25
        }
    },
    {  "auth_service": "ptc",
        "username": "-----",
        "password": "------",
        "location": "Irvine, CA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": ["---------"],
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 200,
        "RELEASE_DUPLICATE": false,
        "DUPLICATE_CP_FORGIVENESS": 0.90,
        "STEP_SIZE": 100,
        "RETURN_START_INTERVAL": 20,
        "MAX_BALL_TYPE": 2,
        "SLOW_BUT_STEALTH": false,
        "AUTO_HATCHING": false,
        "MIN_ITEM_COUNTS": {
            "ITEM_POKE_BALL": 15,
            "ITEM_GREAT_BALL": 25,
            "ITEM_ULTRA_BALL": 95,
            "ITEM_POTION": 5,
            "ITEM_SUPER_POTION": 5,
            "ITEM_HYPER_POTION": 30,
            "ITEM_MAX_POTION": 60,
            "ITEM_RAZZ_BERRY": 20,
            "ITEM_BLUK_BERRY": 10,
            "ITEM_NANAB_BERRY": 10,
            "ITEM_REVIVE": 25
        }
    }
    ]}


Log-in is succesful now! However it now gives me a No fort to walk to error. Is this an API key problem?

**Comment by BoBeR182** [comment]
https://github.com/BoBeR182/PoGoBoWo/issues/62
