### ISSUE TITLE
protobuf install

### ISSUE THREAD

**Issue by JosUijterwaal** [BoBeR182/PoGoBoWo#66]
I'm getting an error running pokebot.py:

File "/home/ubuntu/workspace/PoGoBoWo/pgoapi/__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

please advice on how to solve

**Comment by maddeep** [comment]
Install the requirements from requirements.txt
pip install -r requirements.txt

**Comment by JosUijterwaal** [comment]
sorry to bother you again, I did exactly that. Please check:

SnappCars-MacBook-Pro-2:~ Jos$ git clone https://github.com/BoBeR182/PoGoBoWo
Cloning into 'PoGoBoWo'...
remote: Counting objects: 1301, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1301 (delta 0), reused 0 (delta 0), pack-reused 1293
Receiving objects: 100% (1301/1301), 950.56 KiB | 399.00 KiB/s, done.
Resolving deltas: 100% (625/625), done.
Checking connectivity... done.
SnappCars-MacBook-Pro-2:~ Jos$ cd PoGoBoWo/
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ apt get python 2.7
No Java runtime present, requesting install.
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ apt get jdk 8
No Java runtime present, requesting install.
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ pyhton -V
-bash: pyhton: command not found
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ python -V
Python 2.7.10
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ sudo easy_install pip

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 8.1.2
Downloading https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a
Processing pip-8.1.2.tar.gz
Writing /tmp/easy_install-ae3BdM/pip-8.1.2/setup.cfg
Running pip-8.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ae3BdM/pip-8.1.2/egg-dist-tmp-hTTGC0
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 8.1.2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 1.8MB/s 
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Downloading protobuf-3.0.0-py2.py3-none-any.whl (342kB)
    100% |████████████████████████████████| 348kB 2.2MB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.7MB/s 
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Downloading pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 287kB/s 
Collecting python-gmaps==0.3.1 (from -r requirements.txt (line 7))
  Downloading python_gmaps-0.3.1-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 8))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 2.8MB/s 
Collecting Jinja2==2.7.1 (from -r requirements.txt (line 9))
  Downloading Jinja2-2.7.1.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 2.0MB/s 
Collecting termcolor==1.1.0 (from -r requirements.txt (line 10))
  Downloading termcolor-1.1.0.tar.gz
Collecting six>=1.9 (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->-r requirements.txt (line 2))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 4))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 724kB/s 
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 5))
  Downloading pycryptodomex-3.4.2.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 203kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-gmaps==0.3.1->-r requirements.txt (line 7))
Collecting itsdangerous>=0.21 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 3.4MB/s 
Collecting click>=2.0 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 2.1MB/s 
Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r requirements.txt (line 8))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 1.9MB/s 
Collecting markupsafe (from Jinja2==2.7.1->-r requirements.txt (line 9))
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: geopy, six, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pyproj, python-gmaps, itsdangerous, click, Werkzeug, markupsafe, Jinja2, Flask, termcolor
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/geopy'
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ cp config.json.example config.json
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ vi config.json
SnappCars-MacBook-Pro-2:PoGoBoWo Jos$ python pokebot.py -i 0 --cache
Traceback (most recent call last):
  File "pokebot.py", line 16, in <module>
    from pgoapi import PGoApi
  File "/Users/Jos/PoGoBoWo/pgoapi/__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
