### ISSUE TITLE
Constantly getting [pgoapi] [ERROR] No fort to walk to!

### ISSUE THREAD

**Issue by littleoz2** [BoBeR182/PoGoBoWo#71]
Constantly getting [pgoapi] [ERROR] No fort to walk to!

**Comment by etrevis** [comment]
read [this](https://github.com/BoBeR182/PoGoBoWo/issues/62) download the new-api branch

**Comment by littleoz2** [comment]
Yeah I just found that, was then about to comment on here, thank you
