### ISSUE TITLE
PleaseInstallProtobufVersion3 ??

### ISSUE THREAD

**Issue by inakigloo** [BoBeR182/PoGoBoWo#80]
how could i do it?

**Comment by BoBeR182** [comment]
I don't understand your question.

**Comment by stefanschoemaker** [comment]
I've got the same error

bananapi@lemaker ~/PoGoBoWo $ python run_bot.py -i 1 --cache
Traceback (most recent call last):
File "run_bot.py", line 22, in 
from pogobot import pogobot, web
File "/home/bananapi/PoGoBoWo/pogobot/pogobot.py", line 11, in 
from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType
File "/home/bananapi/PoGoBoWo/pgoapi/__init__.py", line 48, in 
raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

**Comment by BoBeR182** [comment]
What operating system are you on?

**Comment by stefanschoemaker** [comment]
i'm on raspbian

**Comment by BoBeR182** [comment]
You will need, https://github.com/google/protobuf/releases/tag/v3.0.0 no idea if it is supported on ARM architecture. I only run 64bit Linux as my testing and development.
